create table guest (
                       id bigint generated by default as identity,
                       date_of_birth timestamp,
                       first_name varchar(255),
                       last_name varchar(255),
                       passport varchar(255),
                       patronymic varchar(255),
                       photo binary(255),
                       primary key (id)
)

GO

