create table presence (
                          id bigint generated by default as identity,
                          checkin_date timestamp,
                          checkout_date timestamp,
                          guest_id bigint,
                          quarters_id bigint,
                          primary key (id)
)
GO

alter table presence
    add constraint FK98b16x1ji82w7qfldoebimlvm
        foreign key (guest_id)
            references guest

GO

alter table presence
    add constraint FK2fxd7s659nabsvkvu9icmg6up
        foreign key (quarters_id)
            references quarters

GO